baseURL: 'https://nematatu.github.io/'
languageCode: en-us
title: nematatu blog
theme: hugo-PaperMod
taxonomies:
  tag: tags
  category: categories

params:
    defaultTheme: auto 
    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    comments: true
    editPost:
        URL: "https://github.com/nematatu/nematatu.github.io/tree/main/content/"
        Text: "Suggest Changes"
        appendFilePath: true
    homeInfoParams:
        Title: Hi there!ğŸ”¥
        Content: >
            Welcome to nematatu blog!
            - This blog is posted about tech,diary and photos!
        
    socialIcons:
        - name: github
          url: "https://github.com/nematatu/"
        - name: twitter
          url: "https://twitter.com/T_kanntoku/"
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    profileMode:
          enabled: true
          title: nematatu blog
          subtitle: ğŸ’» Tech | ğŸ“’ Diary | ğŸ“¸ Photos | 
          imageUrl: "/img/icon.jpg"
          imageWidth: 200 # custom size
          imageHeight: 200 # custom size
          buttons:
            - name: all posts
              url: "posts/"
            - name: portfolio
              url: "https://nematatu.github.io/website/mysite/"
    twitterID: "@totegamma"
    description: "ãã¤ã­ã®ã€Œã¨ã¨ãŒã‚“ã¾ã€ãŒé‹å–¶ã™ã‚‹å€‹äººã‚µã‚¤ãƒˆã§ã™ã€‚å€‹äººçš„ãªæ—¥è¨˜ã‹ã‚‰é›»å­å·¥ä½œã‚„ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã®ãƒ¡ãƒ¢ã‚’ã€å‚™å¿˜éŒ²ã¨ã—ã¦å…¬é–‹ã—ã¦ã„ã¾ã™ã€‚"
    images: ["/img/ç†Šæœ¬é å¾/sirakawa_1.JPG"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
  main:
    - name: Archives
      url: archives/
      weight: 5

    - name: Search
      url: search/
      weight: 5
    
    - name: Tags
      url: tags/
      weight: 5

    - name: Categories
      url: categories/
      weight: 5
